basePath: /
definitions:
  models.Color:
    properties:
      hexCode:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: backend.battling-pixels.ru
info:
  contact: {}
  description: API for Pixel Battle game
  title: Pixel Battle API
  version: "1.0"
paths:
  /palette:
    get:
      description: Returns list of available colors for the game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
      summary: Get color palette
      tags:
      - palette
swagger: "2.0"
