name: Deploy Go Backend to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/go-server/backend
            git fetch origin
            git reset --hard origin/main

            cat > ../.env << EOF
            CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}
            DOMAIN_URI=${{ secrets.DOMAIN_URI }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}
            EOF

            cp ../.env ./

            docker compose down --remove-orphans
            docker compose up -d --build